FROM node:20-alpine

WORKDIR /app

# Copie des dépendances
COPY package.json package-lock.json* ./
RUN npm install

# Copie du code source
COPY . .

# Build Next.js
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
